reconfigure prettier
bj-rutledge/CRUD-API-Example pull request #77
Opened 2024-08-13 18:54 UTC by SeanAverS

Fixes #74

2024-08-13 20:45 UTC, bj-rutledge requested changes

2024-08-16 05:14 UTC, SeanAverS commented on CRUD-API/.prettierignore
I gotchu

2024-08-16 16:34 UTC, bj-rutledge commented on CRUD-API/.prettierignore
Thank you! I appreciate it. I am happy that you are able to contribute. Feel free to check out any other issues that might seem interesting. You can reach me directly at bjrutledge@outlook.com if you have any questions, or you can reach me through LinkedIn at www.linkedin.com/in/bj-rutledge

2024-08-16 16:35 UTC, bj-rutledge approved these changes
Thank you for your contribution!

2024-08-16 16:35 UTC, merged